.SILENT:

showCompilerVersion.exe: showCompilerVersion.obj
	link /nologo showCompilerVersion.obj /out:showCompilerVersion.exe

showCompilerVersion.obj: showCompilerVersion.c
	cl /nologo /c showCompilerVersion.c /FoshowCompilerVersion.obj
